### ISSUE TITLE
Why is NDPluginCV creating a new DataType attribute?

### ISSUE THREAD

**Issue by MarkRivers** [areaDetector/ADCompVision#34]
NDPluginCV adds a new attribute called DataType:

https://github.com/areaDetector/ADCompVision/blob/03dfe0782b3f43ff3ea1ea7924ba3295d390da54/adcvApp/adcvSrc/NDPluginCV.cpp#L266

I don't understand the need for this, and I think it can lead to confusion.  NDArray already has a dataType field that unambiguously provides the datatype.

I have a plugin chain SIM1>CV1>ROI1>STATS2.  SIM1 is generating UINT16 data. If I set the output datatype of the ROI1 plugin to Automatic I see this with a detailed report of STATS2:
```
epics> asynReport 11 STATS2
...

NDArray  Array address=0x7f94740026d0:
  ndims=2 dims=[10 1 ]
  dataType=3, dataSize=20, pData=0x7f9538000950
  uniqueId=70100, timeStamp=930694270.967465, epicsTS.secPastEpoch=930694270, epicsTS.nsec=977580035
  referenceCount=0
  number of attributes=5

NDAttributeList: address=0x7f9474002860:
  number of attributes=5

...

NDAttribute, address=0x7f94f4002300:
  name=DataType
  description=Data Type
  source type=0
  source type string=NDAttrSourceDriver
  source=Driver
  dataType=NDAttrInt32
  value=3

```
The dataType of the NDArray is 3 (UINT16) and so is the value of the DataType attribute.

However, if I change the ROI1 plugin so the output data type is INT32 I see the following:
```
epics> asynReport 11 STATS2
...

NDArray  Array address=0x7f9538000d50:
  ndims=2 dims=[10 10 ]
  dataType=4, dataSize=400, pData=0x7f9538000f50
  uniqueId=110062, timeStamp=930694675.206727, epicsTS.secPastEpoch=930694675, epicsTS.nsec=216798918
  referenceCount=1
  number of attributes=5

NDAttributeList: address=0x7f9538000ee0:
  number of attributes=5
...

NDAttribute, address=0x7f95380013a0:
  name=DataType
  description=Data Type
  source type=0
  source type string=NDAttrSourceDriver
  source=Driver
  dataType=NDAttrInt32
  value=3
```

Now the NDArray dataType=4 (UINT32), but the DataType attribute is still 3 (UINT16).

I think this is very confusing.  I don't think the NDPluginCV should be creating that attribute unless there is a good reason.

I see that NDPluginBar does the same thing:
https://github.com/areaDetector/ADPluginBar/blob/8f88880d09041da13a6b9becbbdbc8e306c8d0c0/barApp/barSrc/NDPluginBar.cpp#L206

**Comment by jwlodek** [comment]
Hi Mark, I think that was added because for some reason I thought those calls were necessary whenever the `doCallbacksGenericPointer` is called within a driver or plugin. I think that it was added to ADPluginBar and I reused the code in ADCompVision. On Monday I will remove those lines and make sure everything builds and I will make a pull request.

**Comment by MarkRivers** [comment]
You should not be calling doCallbacksGenericPointer directly.  You should call NDPluginDriver::endProcessCallbacks().  https://areadetector.github.io/master/areaDetectorDoxygenHTML/class_n_d_plugin_driver.html#ad2a1210161a2f542f347482aa93f3797

You can look at NDPluginOverlay or most of the other plugins in ADCore for an example:
https://github.com/areaDetector/ADCore/blob/a974f8e71687d8c5ada28b585964acbd1d180d6a/ADApp/pluginSrc/NDPluginOverlay.cpp#L375

Doing it that way is important because it handles 
- Not doing callbacks if ArrayCallbacks is false
- Getting the attributes (you can delete that from your code)
- Sorting output arrays
- Keeping a copy of the last input array so the plugin can be run again on the same array with different settings. 
- Throttling the output rate
- Updating statistics on disordered arrays and dropped output arrays

That call should come at the end of your processCallbacks() function.

**Comment by MarkRivers** [comment]
I just did a search for `doCallbacksGenericPointer` in ADCore/ADApp/pluginSrc/*.cpp

```
corvette:ADCore/ADApp/pluginSrc>grep doCallbacksGenericPointer *.cpp
NDPluginAttribute.cpp:  doCallbacksGenericPointer(pTimeSeriesArray, NDArrayData, 1);
NDPluginCircularBuff.cpp:          doCallbacksGenericPointer(pArrayCpy, NDArrayData, 0);
NDPluginCircularBuff.cpp:      doCallbacksGenericPointer(preBuffer_->readFromStart(), NDArrayData, 0);
NDPluginCircularBuff.cpp:        doCallbacksGenericPointer(preBuffer_->readNext(), NDArrayData, 0);
NDPluginDriver.cpp:        doCallbacksGenericPointer(pArrayOut, NDArrayData, 0);
NDPluginDriver.cpp:                doCallbacksGenericPointer(pListElement->pArray_, NDArrayData, 0);
NDPluginStats.cpp:    doCallbacksGenericPointer(pTimeSeriesArray, NDArrayData, 1);
NDPluginTimeSeries.cpp:    doCallbacksGenericPointer(pArrayOut, NDArrayData, numSignals_);
NDPluginTimeSeries.cpp:      doCallbacksGenericPointer(pArray, NDArrayData, signal);
```

- `NDPluginAttribute` and `NDPluginStats` only call `doCallbacksGenericPointer()` for the time-series arrays, not for the normal NDArray. 
- `NDPluginTimeSeries` is doing callbacks in individual asyn addr fields, so it is special. 
-  `NDPluginCircularBuff` is also special because it does not do callbacks each time it processes, but rather only when it is triggered, and then it may do many callbacks in a single processing.

All other plugins simply call endProcessCallbacks(), rather than `doCallbacksGenericPointer()`.

**Comment by jwlodek** [comment]
I'll make sure to change this on Monday. I originally based these plugins on ADPluginEdge which does the `doCallbacksGenericPointer` call which is why mine had this as well.
https://github.com/areaDetector/ADPluginEdge/blob/eff0f7107385ff32bdedce087203b3ed259c4a62/edgeApp/edgeSrc/NDPluginEdge.cpp#L259

**Comment by MarkRivers** [comment]
Thanks for pointing out the issue with ADPluginEdge.  That was last modified 4 years ago, while endProcessCallbacks() was added to NDPluginDriver in ADCore R3-0, 2 years ago.

I have fixed ADPluginEdge with this change:
```
diff --git a/edgeApp/edgeSrc/NDPluginEdge.cpp b/edgeApp/edgeSrc/NDPluginEdge.cpp
index f56df74..80baf3b 100644
--- a/edgeApp/edgeSrc/NDPluginEdge.cpp
+++ b/edgeApp/edgeSrc/NDPluginEdge.cpp
@@ -255,12 +255,8 @@ void NDPluginEdge::processCallbacks(NDArray *pArray)
     inData  = (unsigned char *)detected_edges.data;
     outData = (unsigned char *)pScratch->pData;
     memcpy(outData, inData, arrayInfo.nElements * sizeof(unsigned char));
-    this->getAttributes(pScratch->pAttributeList);
-    doCallbacksGenericPointer(pScratch, NDArrayData, 0);
   }
-
-  if (NULL != pScratch)
-    pScratch->release();
+  endProcessCallbacks(pScratch, false, true);

   callParamCallbacks();
 }
```

Note that I still test arrayCallbacks because we can avoid the memcpy if it is false.  But the calls to getAttributes, doCallbacksGenericPointer, and pScratch->release() can all be eliminated.

**Comment by jwlodek** [comment]
I have been working on these fixes for ADCompVision, but I have run into an issue. 

When the plugin does processing, it often has to change the data type / Color Mode of the output from the original image. For example, when thresholding, the output will be an 8 bit grayscale image, no matter the color mode or bit depth of the input. However, when I output this image as is, the other plugins still read it as an RGB image of whichever bit depth it was originally. The image plugin still sees 8 bit RGB instead of 8 bit mono for example on the color camera I am testing with thresholding.

In NDPluginColorConvert I found this: https://github.com/areaDetector/ADCore/blob/a974f8e71687d8c5ada28b585964acbd1d180d6a/ADApp/pluginSrc/NDPluginColorConvert.cpp#L595, but I thought that was what we were trying to avoid. Is there another solution to this problem that I am missing?

All of the functions that do not affect the data type and color mode seem to be working correctly.

**Comment by MarkRivers** [comment]
I was not suggesting removing the code to set the ColorMode. That is necessary. I was only suggesting to remove the attribute DataType since that is redundant with the information in the NDArray object itself.

**Comment by jwlodek** [comment]
Ah I see. I'll add that call back in then. Thank you

**Comment by MarkRivers** [comment]
Is it possible to have your call to endProcessCallbacks() in the processCallbacks() function itself? That’s how it is done in NDPluginEdge, and I think it makes the code clearer.

**Comment by jwlodek** [comment]
Yes that is how I am trying to do it. I moved the pScratch allocation to `processCallbacks()` as well, and I just pass the pointer to `mat2NDarray()` to copy the actual data.

**Comment by jwlodek** [comment]
I have made a pull request that contains the discussed changes along with another CV function that can be used to record video files using areaDetctor cameras: https://github.com/areaDetector/ADCompVision/pull/36
It also adds support for threading as discussed in issue #35
I've tested it with `simDetector` and with an `ADUVC` camera, and it all seems to work OK. The one caveat is that the video recording function and subtract functions are not thread safe, and are thus not affected by increasing the max thread count. I will make a pull request to `ADCore` editing the `commonPlugins` file to add the `MAX_THREADS` param to the `NDCVConfigure` call

**Comment by jwlodek** [comment]
Closing since the issues discussed here were fixed with https://github.com/areaDetector/ADCompVision/pull/36
