### ISSUE TITLE
Add support for maxThreads>1

### ISSUE THREAD

**Issue by MarkRivers** [areaDetector/ADCompVision#35]
All plugins should support maxThreads>1 if it is feasible and if there would be a performance gain.

I don't see any reason why it should not be feasible for NDPluginCV.  It only processes a single image at a time (unlike for example NDPluginProcess which needs to know about the previous image), and that should be able to be done in a thread-safe manner.  OpenCV operations are likely to be time-consuming and a linear improvement in throughput with number of threads could be expected.

The OpenCV library claims to be thread-safe.

**Comment by jwlodek** [comment]
Closing since threading support was added with https://github.com/areaDetector/ADCompVision/pull/36
